name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '*.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '*.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Deno environment
      uses: denolib/setup-deno@v1.3.0
      with:
        deno-version: v1.x
      
    - name: Run test
      run: deno test --allow-read
